### ISSUE TITLE
What is the status of this package?

### ISSUE THREAD

**Issue by schungx** [rhaiscript/rhai-url#1]
Would you like to contribute it into the `rhaiscript` org?

Do you plan on adding network access to it?

**Comment by lucacicada** [comment]
I have been keeping an eye on new versions of Rhai to ensure this package do not break and I have not encountered any issues so far.

Regarding the network capabilities, my original idea was to provide a simple interface for dealing with URLs in Rhai that is similar to the one found in web browsers.
Therefore, I do not believe that adding network capabilities to this specific package is necessary, it should be implemented elsewhere, maybe by using this to deal with URLs.

As for contributing, Rhai is a great, however I feel it lacks some utilities. 

With this package, I have attempted to address this specific issue and provide a useful tool for working with URLs in Rhai.

So I am more than happy to contributing to rhaiscript in case this package is decent and my explanation align properly with Rhai's goals.

**Comment by schungx** [comment]
That's great.  I can make you a contributor to `rhaiscript` and you can decide to move this repo there and publish it as part of the Rhai ecosystem!

**Comment by schungx** [comment]
I also suggest that you review other libs in the org and stick to a similar structure so that it becomes easier for users.

When you have moved the repo, I'll add an entry in the Book announcing this!

**Comment by lucacicada** [comment]
That's perfect!
