### ISSUE TITLE
API documentation 

### ISSUE THREAD

**Issue by schungx** [rhaiscript/rhai-url#2]
Would be good to include docs on the API in the README.

You may also consider the method used by many libraries in this org to auto-gen docs based on doc-comments.

**Comment by schungx** [comment]
BTW, an entry has been added to the Book about `rhai-url`:

https://rhai.rs/book/lib/rhai-url.html

**Comment by lucacicada** [comment]
Docs should now be auto-generated, I went ahead and also updated tests and the README. 

On a second thought, I think the docs are not quite good enough, nor they do cover common use cases, I would like to keep this issue open to continue working on improving the docs and include some example code.

**Comment by schungx** [comment]
It seems that the auto-gen docs program does not properly handle property getters and setters, which it should.

I'll fix it in a bit.

**Comment by schungx** [comment]
@lucacicada   I have updated the build script to properly handle property getters and setters.  They should now display correctly.

I have also slightly modified the doc-comments style to be consistent with other libraries in the org.

BTW, I see that the `no_index` feature is never used in the project.  It can probably be removed unless you have portion of the API that works on arrays (which doesn't appear to be so).
