### ISSUE TITLE
Return Array instead of Vec<ImmutableString>

### ISSUE THREAD

**Issue by schungx** [rhaiscript/rhai-url#3]
```rust
    pub fn query_gets(url: &mut Url, key: &str) -> Vec<ImmutableString> {
        url.query_pairs()
            .filter(|(name, _)| name == key)
            .map(|(_, value)| ImmutableString::from(value.as_ref()))
            .collect()
    }
```

Probably should return `Array`, because `Vec<ImmutableString>` is an opaque custom type that won't have built-in support from Rhai.

```rust
    pub fn query_gets(url: &mut Url, key: &str) -> Array {
        url.query_pairs()
            .filter(|(name, _)| name == key)
            .map(|(_, value)| ImmutableString::from(value.as_ref()).into())
            .collect()
    }
```

**Comment by lucacicada** [comment]
Should I also keep the `#[cfg(not(feature = "no_index"))]`?

[rhai-url/src/url.rs#L309C1-L316C6](https://github.com/rhaiscript/rhai-url/blob/b35b61839cb5e4866b11acc32e55353b6f1baddd/src/url.rs#L309C1-L316C6)

**Comment by schungx** [comment]
Hhhh.... Good point.

Taking style from other Rhai libs, maybe an `array` feature that will turn on this call instead.

It is usually best to keep features strictly additive.

**Comment by lucacicada** [comment]
I think that, in this case, we are actually fixing a bug rather than removing a feature.

If someone has `no_index`, most likely won't use arrays, thus neither function `query_gets`, which returns an array.

We could release a 0.0.4 addressing this, with the corrected behavior.

**Comment by schungx** [comment]
It goes either way...  `no_index` is a historical mistake that unfortunately must be maintained for compatibility.

New libs I would strongly suggest to make features additive instead, which means an `array` feature that is turned on by default.

**Comment by lucacicada** [comment]
I went ahead with your proposal, I have also dropped the unused `no_index` feature flag, I will not release the 0.0.4 yet until we are actually happy with the changes.

**Comment by schungx** [comment]
I think it looks good!
